name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Fetch Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Build Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build
        run: npm install -g pnpm && pnpm install && pnpm release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ matrix.os }}
          path: releases
