name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Fetch Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Build Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm install -g pnpm && pnpm install && pnpm release
